### ISSUE TITLE
Access Violation when slicing colored model

### ISSUE THREAD

**Issue by SwagDad99** [bambulab/BambuStudio#1029]
**Describe the bug**
After spending hours coloring a detailed model, it  gets an 'Access Violation' when slicing.  In the thumbnail in the upper right corner of the preview window while slicing, it gets the error when it gets down to the first colored area of the model.  The progress text says "35% Generating Infill Toolpaths"

**3mf File for This Bug**
The file slices fine before coloring.  The STL is a paid file, and I am unable to share it without permission.

**To Reproduce**
1. Spend hours coloring a model in great detail.  (Perhaps generating too much detailed color?)
2. Click on 'Slice'
3. See error 'Access Violation'

**Expected behavior**
Successful Slice and ability to print.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows

**Comment by SaltWei** [comment]
Which windows version are you using?

Could you try following binary https://www.dropbox.com/s/cm3a4v0x9vc5ixp/Bambu_Studio_win-v01.04.01.52-20221226111441.zip?dl=0
which includes symbol table for generating slicing log.
and try to slice again.

when it crashes
please help to share the log file and the crash log file under C:\Users\user.name\AppData\Roaming\BambuStudio\log
such as followings:
image

**Comment by SwagDad99** [comment]
I am using Windows:
Edition    Windows 11 Home
Version    22H2
Installed on    ‎5/‎7/‎2022
OS build    22616.1
Experience    Windows Feature Experience Pack 1000.22632.1000.0

It still fails with the same error.  Attached are the logs.

Don

**Comment by SaltWei** [comment]
> Attached are the logs.

Sorry, I can't see any attachment. May be limited by github.
Could you please send the log to my email: salt.wei@bambulab.com ?

**Comment by SwagDad99** [comment]
I just sent them.

**Comment by SaltWei** [comment]
Not sure what's the problem, I have refreshed email for many times but still get nothing except message from github. Have contacted with IT guys wo check whether has networt issue
![image](https://user-images.githubusercontent.com/110660407/212253833-6d757b10-24db-4317-a214-e8fd7bf68021.png)

**Comment by 99berend99** [comment]
I got the same error. Also a colored model.

Mine got stuck on 15%, generating walls.

![image](https://user-images.githubusercontent.com/122634702/212382828-8ad57248-7449-4252-9892-16d9efdc28a7.png)

**Comment by SaltWei** [comment]
> I got the same error. Also a colored model.
> 
> Mine got stuck on 15%, generating walls.

Thank you very much for reporting this issue and sharing the 3MF file!

For this 3mf file, this is an known issue caused by fuzzy skin and we have fixed in internal version.

The fix will be included in the next user version, which will come soon!

**Comment by SwagDad99** [comment]
So, my model does not have fuzzy skin.  That means my issue is separate, and not fixed in the next release?

**Comment by SaltWei** [comment]
> So, my model does not have fuzzy skin. That means my issue is separate, and not fixed in the next release?

There are no abnormal log in the file you shared.
Is there log file which name begin with "crash_" after using the binary I shared to slice?

**Comment by SaltWei** [comment]
It would be very convenient to debug the issue if had one 3mf shared which has no copyright.

**Comment by SwagDad99** [comment]
I am sorry, but the only two 3mf files that I have had this issue with are purchased files.  You could contact the Patreon and see if he will allow me to share it with you. https://www.myminifactory.com/users/dansopala
Tell him that it is the Coal Miner Ant.

Don

**Comment by SwagDad99** [comment]
I now have the error with a file I can share...!  For some reason the printer/nozzle type doesn't want to stay X1C .04, and the layer height should be 0.20 standard.
[Print-in-Place - Small-Colored.zip](https://github.com/bambulab/BambuStudio/files/10432213/Print-in-Place.-.Small-Colored.zip)

**Comment by SaltWei** [comment]
> I now have the error with a file I can share...! For some reason the printer/nozzle type doesn't want to stay X1C .04, and the layer height should be 0.20 standard.

Thank you very much and now we can reproduce this issue.

**Comment by SaltWei** [comment]
@zhimin-zeng-bambulab Please check this array which should be 8x8,but it's 4x4 now
![image](https://user-images.githubusercontent.com/110660407/212848521-1dc7c3db-de19-4d4d-a039-5c3e5dfcd521.png)
![2qah1KdIEi](https://user-images.githubusercontent.com/110660407/212848543-5a9d0e49-f514-4859-98d3-e68da98f0339.jpg)

**Comment by SwagDad99** [comment]
I went to flushing volumes, and yes, there are only 4 on the left, and 4 on the top...  How do I fix that?

Don

**Comment by SaltWei** [comment]
Add one filament and then delete it. The array will be updated to be 8x8. We think this is one issue caused by UI and will fix it

**Comment by SwagDad99** [comment]
It worked!  Thank you!

Don
