### ISSUE TITLE
Unable to select PA profile or enter Factor K

### ISSUE THREAD

**Issue by patrickcheah** [bambulab/BambuStudio#4275]
### Bambu Studio Version

1.9.2.57

### Where is the application from?

Bambu Lab Official website

### OS version

macOS Sonoma 14.5

### Additional system information

Apple M1 Pro MacBook Pro 2021

### Printer

Bambu P1S

### How to reproduce

In the Device tab, interacting on the filaments on my AMS:
1) Factor K has no value
2) Drop down for PA profile is not working
<img width="595" alt="Screenshot 2024-06-13 at 11 50 10 AM" src="https://github.com/bambulab/BambuStudio/assets/658805/976b10d5-0c96-4703-92c5-f6d63ca48b8b">
<img width="593" alt="Screenshot 2024-06-13 at 11 50 04 AM" src="https://github.com/bambulab/BambuStudio/assets/658805/e0479382-b70f-4455-872e-6f545c8aca1d">

### Actual results

In the Device tab, interacting on the filaments on my AMS:
1) Factor K has no value
2) Drop down for PA profile is not working
<img width="595" alt="Screenshot 2024-06-13 at 11 50 10 AM" src="https://github.com/bambulab/BambuStudio/assets/658805/976b10d5-0c96-4703-92c5-f6d63ca48b8b">
<img width="593" alt="Screenshot 2024-06-13 at 11 50 04 AM" src="https://github.com/bambulab/BambuStudio/assets/658805/e0479382-b70f-4455-872e-6f545c8aca1d">

### Expected results

1) Factor K value should be present and I can update it
2) PA profile should be available to be selected with the dropdown

### Project file & Debug log uploads

[Uploading Magsafe Phone and Watch Stand(2).3mf.zip…]()

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by gitbreiti** [comment]
Same problem here. Seems to have come with the new firmware update (01.06.00.00) for P1P/P1S

**Comment by TaylorN15** [comment]
> I have found it. It is not a firmware error. You can create a profile under Dynamic Flow Calibration and then select it.

I found this also, but my issue is that you have to create a profile for every type of filament you have. Even though I have done this before, it wasn't saved like now. I would prefer to be able to choose a profile _or_ enter a value manually.

**Comment by TinyMito** [comment]
I just updated Bambu Studio 1.9.2.57 and latest beta firmware on P1S... it lost all the preset K values under Manage Result in Calibration tab page.

**Comment by zhimin-zeng-bambulab** [comment]
The new P1P/S firmware is the same as the X series. It stores the k value on the machine and manages it through the "Manage Results" of Calibration page. If you already know the k value, you can add it directly here.
![image](https://github.com/bambulab/BambuStudio/assets/120697589/92376f21-7e5e-4f1d-a153-fc57be5af93f)

**Comment by fatboy1271** [comment]
Thank you @zhimin-zeng-bambulab! After going to Calibration > Manage Result I was able to select it 🤘🤘

**Comment by tjc2005** [comment]
This is still happening, very frustrating!

**Comment by zhimin-zeng-bambulab** [comment]
@tjc2005  What is your problem? Could you describe it in detail? Can't the above method solve your problem?

**Comment by tjc2005** [comment]
> @tjc2005 What is your problem? Could you describe it in detail? Can't the above method solve your problem?

Drop down for PA profile is not working in AMS menu.

I have to close Bambu studio and reopen, sometimes that works, but it seems to be luck of the draw wether the drop down menu decides to work or not.

**Comment by JonasKuschel** [comment]
I have the same bug. I have setup the k-values in the Calibration Tab, however whenever I restart the computer or printer or idk when this happens. The results just won't show up. When I go to Calibration > Manage Results and wait for a short time until the Calibrations are loaded, I can go back to the device tab and now they become visible.

**Comment by OzDruiD** [comment]
This is also now happening to me .. anyone found a better fix that going the  workaround

Workaround-
"Calibration > Manage Results and wait for a short time until the Calibrations are loaded, I can go back to the device tab and now they become visible.

**Comment by hemai249** [comment]
@OzDruiD Hi!  We have already fixed this issue in the new version. you can updating to the latest Studio and firmware versions.

**Comment by GKMoritz** [comment]
@hemai249 This is definitely not fixed as I had this issue again just today all the PA profiles are gone after restarting PC and Printer. Very frustrating and a waste of filament.

**Comment by wkeifenheim** [comment]
I am another user experiencing this issue on the latest release `2.5.0.66`
