### ISSUE TITLE
Fuzzy skin modifier adds internal walls

### ISSUE THREAD

**Issue by Arachnid** [bambulab/BambuStudio#5178]
### Bambu Studio Version

1.9.7.52

### Where is the application from?

Bambu Lab github releases

### OS version

Windows 11

### Printer

X1C

### How to reproduce

1. Create a cube
2. Create a modifier that intersects the cube
3. Set the fuzzy skin property for the modifier to on

### Actual results

Extraneous internal walls are generated along the boundary of the modifier object.

![Screenshot 2024-11-11 095254](https://github.com/user-attachments/assets/0ef499fc-83a6-4b45-bd9f-7407e51499f2)

### Expected results

The modifier should affect the existing walls of the cube, but not generate new ones.

### Project file & Debug log uploads

See reproduction steps above.

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by msxrx** [comment]
This has been fixed in Orca and Prusa Slicer: https://github.com/SoftFever/OrcaSlicer/pull/6759

**Comment by QingZhangBambu** [comment]
I will add it to our feature pool, concerned staff will review it.

**Comment by Kacper1263** [comment]
still not fixed... any updates? This is another reason why i need to use Orca

**Comment by BrettThePark** [comment]
@QingZhangBambu > I will add it to our feature pool, concerned staff will review it.

Please fix this BUG. This is not a "feature" addition, it is a regression.

**Comment by vanowm** [comment]
> Please fix this BUG. This is not a "feature" addition, it is a regression.

It seems @QingZhangBambu doesn't understand the difference between a bug and feature request...every issue I see they involved they replaced `bug` tag with `feature`
