### ISSUE TITLE
Object stacking broken after v01.09.07.52

### ISSUE THREAD

**Issue by dremugit** [bambulab/BambuStudio#5303]
### Bambu Studio Version

v01.10.00.89 and v01.10.01.50

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 10

### Printer

X1 Carbon

### How to reproduce

Open shelftag plabasic base.stl, click Objects (vs Global), right-click shelftag plabasic base.stl, click Add part, Load, shelftag plabasic text.stl

### Actual results

On v01.10.00.89+, the two parts sit on the build plate and don't stack.

### Expected results

On v01.09.07.52, the two parts stack tidily, text on top of base and centered (well, slightly offset by design for the mounting holes.) 

### Project file & Debug log uploads

[workingandbrokenprojects.zip](https://github.com/user-attachments/files/17786900/workingandbrokenprojects.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by dremugit** [comment]
[stl files.zip](https://github.com/user-attachments/files/17787161/stl.files.zip)

Oops, don't know if these are in the project files or not, so added these separately.

**Comment by Haidiye00** [comment]
Hello, can you download ScreenToGif software and record a GIF of the operation video and upload it? Thank you

**Comment by dremugit** [comment]
[gifs.zip](https://github.com/user-attachments/files/17798253/gifs.zip)

One each for v01.10.01.50 ("broken") and v01.09.07.52 ("working")

**Comment by ClaudioVarandas** [comment]
can confirm, object stacking by adding part is not working anymore, it adds the adds the part aside the parent object.

**Comment by JohnSmithCYM** [comment]
Confirm,it will be fixed in next Github Release version.

**Comment by Haidiye00** [comment]
Hello, we have released software V2.0. Please download and use it
https://github.com/bambulab/BambuStudio/releases/tag/v02.00.00.95

**Comment by Haidiye00** [comment]
Hello, please use the latest version, thank you.
https://github.com/bambulab/BambuStudio/releases/tag/v02.00.02.57

**Comment by dremugit** [comment]
Reintroduced in v02.02.00.85. That is, v02.01.01.52 works, but 2.02.00.85+ are broken, same as above. Still broken as of v02.02.02.56.
