### ISSUE TITLE
P1P with Upgrade Kit no longer accepted as P1S

### ISSUE THREAD

**Issue by bjoernmayer** [bambulab/BambuStudio#6148]
### Bambu Studio Version

2.0.0.95

### Where is the application from?

Bambu Lab Official website

### OS version

macOS 15.3.2 (24D81)

### Printer

Bambu Lab P1(P/S)

### How to reproduce

1. Get P1P
2. Upgrade P1P with official kit to P1S
3. Try to choose P1S as your printer in Bambu Studio
4. Try to sync AMS colors

### Actual results

Error is shown:
![Image](https://github.com/user-attachments/assets/c8e9565e-11c0-4370-9bfd-19c8b35330be)

Before version 2.0 this was absolutely no problem.

Why do I want to choose P1S?
- I want to use all features of the P1S. That's why I installed the UPGRADE kit. I am afraid, that all extra fans won't be used, when choosing P1P as printer

### Expected results

Let me handle an upgraded P1P like a P1S

### Project file & Debug log uploads

Not needed

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by MedoG27** [comment]
I have your same problem

**Comment by Haidiye00** [comment]
Hello，We have optimized the behavior in the internal version：p1s and p1p are compatible machines， If your preset is p1s and the connected printer is p1p, both can initiate AMS mapping and printing tasks.
We have fixed it and will release a new version as soon as possible~

**Comment by Haidiye00** [comment]
Hello, we have fixed this issue. Please download the latest version to use.
https://github.com/bambulab/BambuStudio/releases/tag/v02.00.01.50
We apologize for any inconvenience caused and will continue to improve the quality of our software.

**Comment by mbaran5** [comment]
I am seeing a regression of this error in the latest version of studio. I have a P1P with the upgrade kit. 

![Image](https://github.com/user-attachments/assets/c547817f-d7ae-4b67-aaec-db408dcab719)

**Comment by mbaran5** [comment]
@Haidiye00 - I am still seeing this even in the most current release. Please advise. I have a P1P with official kit selected in the menu.

![Image](https://github.com/user-attachments/assets/dace916a-79c3-42fc-ba3e-3969581834ee)

**Comment by Haidiye00** [comment]
> 我在最新版本的 Studio 中看到了此错误的回归。我有一个带有升级套件的 P1P。
> 
> ![Image](https://github.com/user-attachments/assets/c547817f-d7ae-4b67-aaec-db408dcab719)

Hello, may I ask which version you are using?

**Comment by mbaran5** [comment]
> > 我在最新版本的 Studio 中看到了此错误的回归。我有一个带有升级套件的 P1P。
> > ![Image](https://github.com/user-attachments/assets/c547817f-d7ae-4b67-aaec-db408dcab719)
> 
> Hello, may I ask which version you are using?

I posted a new bug with all of the relevant details 

https://github.com/bambulab/BambuStudio/issues/7395
