### ISSUE TITLE
Crash on macOS 15.5 after wake from sleep: SIGSEGV in libbambu_networking.dylib (MQTT on_connected callback)

### ISSUE THREAD

**Issue by bearclaw92** [bambulab/BambuStudio#7181]
### Bambu Studio Version

v2.01.00.59

### Where is the application from?

Bambu Lab Official website

### OS version

macOS 15.5 (24F74) — Apple M3 Pro, 18GB RAM

### Additional system information

CPU: Apple M3 Pro  
Memory: 18GB unified LPDDR5  
Display: Dual monitor setup (DELL 1440p + MacBook Retina)  
GPU: Apple Integrated (Metal support enabled)  

### Printer

Bambu lab a1 mini combo

### How to reproduce

1. Launch Bambu Studio
2. Leave computer idle or manually put it to sleep
3. Wake the computer
4. App crashes within seconds (or upon network reconnection attempt)

### Actual results

App immediately crashes upon wake, SIGSEGV at 0x0000000000000000 inside libbambu_networking.dylib.

### Expected results

App should reconnect gracefully or delay reconnection logic until full network stack is ready after wake.

### Project file & Debug log uploads

[log.zip](https://github.com/user-attachments/files/20641095/log.zip)

[BAMBUCRASH.3mf.zip](https://github.com/user-attachments/files/20641106/BAMBUCRASH.3mf.zip)

### Checklist of files to include

- [x] Log file
- [x] Project file

**Comment by perlbo** [comment]
same Problem here MacBook Air M4

**Comment by brunojppb** [comment]
I've been experiencing the same. MacBook Pro M1, Sequoia 15.5

**Comment by ccann** [comment]
Same here

**Comment by BoBoYu-BamBu** [comment]
@brunojppb @ccann @bearclaw92 Thank you for your feedback. We have already fixed this issue and released a new plugin: V2.1.0.56. Please update the plugin and try again.

**Comment by brunojppb** [comment]
I can confirm that with the new release it has fixed the issue for me! Thank you so much!

**Comment by perlbo** [comment]
Problem still exist. But now Bambustudio does not close and crash but it freezes now after wake up.

**Comment by BoBoYu-BamBu** [comment]
> 问题仍然存在。不过现在 Bambustudio 不会关闭和崩溃，只是唤醒后会卡住。

@perlbo Sorry, this is another issue. Is it similar to  https://github.com/bambulab/BambuStudio/issues/7320?

**Comment by perlbo** [comment]
> > 问题仍然存在。不过现在 Bambustudio 不会关闭和崩溃，只是唤醒后会卡住。
> 
> [@perlbo](https://github.com/perlbo) Sorry, this is another issue. Is it similar to [#7320](https://github.com/bambulab/BambuStudio/issues/7320)?
I have a m4 macbookair and shutdown is no Problem

**Comment by XinZhangBambu** [comment]
@perlbo Thank you for your feedback. Your feedback will be followed at #7291.  

![Image](https://github.com/user-attachments/assets/912d4f5d-9e60-442e-a710-3546ced6d72c)
