### ISSUE TITLE
Avoid Crossing Walls isn't actually respected

### ISSUE THREAD

**Issue by iscofield** [bambulab/BambuStudio#7240]
### Bambu Studio Version

2.1.0.59

### Where is the application from?

Bambu Lab Official website

### OS version

MacOS 15.4.1

### Additional system information

CPU - M4
RAM - 32GB

### Printer

Both X1C and H2D

### How to reproduce

1. Import any gridfinity box STL with a center wall
2. Check / Un-check "Avoid Crossing Walls"
3. Slice model
4. Check travel to view travel lines
5. Observe all the travel lines that cross walls, ignoring the setting

### Actual results

The sliced model is full of travels across walls, which results in absolutely horrendous print quality.

<img width="497" alt="Image" src="https://github.com/user-attachments/assets/6c40b8b5-ae75-4b6f-a2e1-f128201d989b" />

Pictures of the results of all the travels:

![Image](https://github.com/user-attachments/assets/1e87302e-fa86-4a42-8a98-f332cfb104fb)
![Image](https://github.com/user-attachments/assets/ca25a76b-3035-45e2-a2d4-22cdf6f14591)
![Image](https://github.com/user-attachments/assets/c6b9a5e4-6997-486f-8405-f9206107f667)

### Expected results

To not cross walls, which results in very poor print quality.

Using the same STL / 3MF in Orca Slicer and checking "Avoid Crossing Walls", the setting is respected:

<img width="504" alt="Image" src="https://github.com/user-attachments/assets/95768fff-a506-4846-a6d8-5482601ba768" />

When printing via Orcaslicer on my X1C and not having it cross walls, the print quality is flawless.

### Project file & Debug log uploads

Project File - [kitchen_gridfinity.3mf.zip](https://github.com/user-attachments/files/20700013/kitchen_gridfinity.3mf.zip)

Logs - [Archive.zip](https://github.com/user-attachments/files/20700057/Archive.zip)

### Checklist of files to include

- [x] Log file
- [x] Project file

**Comment by Intec-bambu** [comment]
I have started analyzing this issue. Thank you for the feedback.

**Comment by iscofield** [comment]
Tried downgrading to 2.03 to see if that resolved the issue, as the newer version of BS did make changes to the "avoid crossing walls" setting, but I still see the same behavior.

**Comment by iscofield** [comment]
Any updates here? The weakest part of my H2D is the fact that it has to use Bambu Slicer and I can’t use other slicers, like Orca. I’m hamstrung here as the print quality is pretty bad on this printer and I can’t do anything to fix it here.

**Comment by Intec-bambu** [comment]
> Any updates here? The weakest part of my H2D is the fact that it has to use Bambu Slicer and I can’t use other slicers, like Orca. I’m hamstrung here as the print quality is pretty bad on this printer and I can’t do anything to fix it here.

Hi, apologies for the delay! This feature touches a lot of models and requires careful testing and iteration to avoid unexpected side effects. We're actively working on it and appreciate your patience in the meantime.

**Comment by MikiZed** [comment]
I have the same issue, it's not just gridfinity models.
Avoid crossing walls doesn't seem to have any effect in Bambu studio 20.1.1.52

I am surprised no one faced this sooner, it's kind of a big deal... 

Orca slicer on the other hand seem to be working as expected


![Image](https://github.com/user-attachments/assets/91d975a7-1dd0-40b9-9ee7-001f724be96d)
![Image](https://github.com/user-attachments/assets/e7e8d0d6-c3b9-48ee-8c29-4840c7ce4459)

This is orca slicer
![Image](https://github.com/user-attachments/assets/2db487bd-5ff8-4985-87f6-01bc425e1285)

**Comment by Intec-bambu** [comment]
> I have the same issue, it's not just gridfinity models.我也有同样的问题，不仅仅是 Gridfinity 模型。 Avoid crossing walls doesn't seem to have any effect in Bambu studio 20.1.1.52避免穿墙在 Bambu studio 20.1.1.52 中似乎没有任何效果
> 
> I am surprised no one faced this sooner, it's kind of a big deal...我很惊讶没有人更早遇到这个问题，这其实挺重要的...
> 
> Orca slicer on the other hand seem to be working as expected另一方面，Orca 切片器似乎按预期工作
> 
> ![Image](https://github.com/user-attachments/assets/91d975a7-1dd0-40b9-9ee7-001f724be96d) ![Image](https://github.com/user-attachments/assets/e7e8d0d6-c3b9-48ee-8c29-4840c7ce4459)
> 
> This is orca slicer  这是 Orca 切片器 ![Image](https://github.com/user-attachments/assets/2db487bd-5ff8-4985-87f6-01bc425e1285)

Please upload the 3mf file, thanks

**Comment by MikiZed** [comment]
I don't know if you want the 3mf as in the print profile or just the 3d model,  3mf files can't be uploaded to github you can use this link
https://we.tl/t-uHDh3seT7Y

I did some testing and I have uploaded 3 different print profiles

1.  It's from orcaslicer and it's working as expected
2. It's from bambulab with default wall avoiding settings (200mm). In the pic below you can see the weird behaviour of the travel path being just outside the walls resulting in print quality issues
![Image](https://github.com/user-attachments/assets/fd8c46b8-d4ef-4fb6-ac14-709285bfec1b)

3. It's from bambulab with tweaked wall avoiding settings, where you can see the travel path just crossing the models like in my original comment. The same behaviour happens if you use 1, 9999, 99% 9999% in the max detour lenght. 


In each print profile there are 3 3D models, I wanted to make sure the problem wasn't because of the original 3d model. 
I originally imported a mesh directly from cad then cut it in the slicer resulting in manifold error. So to test things out there are 3 build plates:

1. Cut directly in CAD, then imported in the slicer with no further modifications
2. Imported a bigger model from cad, cut it in slicer,  without fixing the manifold error
3. Imported a bigger model from cad, cut it in slicer,  and fixed the manifold error

The behaviour seems to be exactly the same but I tought you might want to check for yourself

**Comment by fhufi** [comment]
Related issue #7452 on Windows version

**Comment by sakomoto987** [comment]
Hi everyone,

Just wanted to share some findings regarding the Avoid Crossing Wall feature in Bambu Studio, in case others are running into similar issues.

I’ve tested the recent 2.2.0 Public Beta, and while there are some improvements — notably, the nozzle no longer travels outside the model on curved areas — the core issue still persists: travel moves are still crossing internal walls unnecessarily, even when Avoid Crossing Wall is enabled.

You can see this clearly in the screenshots attached. These crossings occur in situations where the path planner could clearly avoid them. What makes this especially problematic is when printing flexible materials like TPU, where clean travel paths really matter for quality as mentioned.

One additional detail: I’m using a custom seam setting, but the exact same configuration works perfectly in OrcaSlicer, and was previously handled correctly in older versions of Bambu Studio.

To summarize:
	•	Bambu Studio 2.2.0 beta improves outer travel behavior on curves ✅
	•	Avoid Crossing Wall still doesn’t prevent unnecessary internal wall crossings ❌
	•	Custom seam settings may play a role, but it’s not an issue in OrcaSlicer or earlier Bambu Studio releases

Happy to share more info if needed — hoping this helps others or leads to further improvements!

![Image](https://github.com/user-attachments/assets/5c79cec5-fc97-47e1-a284-e3ccc392c9b4)
![Image](https://github.com/user-attachments/assets/3d1f97fa-b8f7-473d-81c5-61a3e927865a)

**Comment by Intec-bambu** [comment]
> Hi everyone,
> 
> Just wanted to share some findings regarding the Avoid Crossing Wall feature in Bambu Studio, in case others are running into similar issues.
> 
> I’ve tested the recent 2.2.0 Public Beta, and while there are some improvements — notably, the nozzle no longer travels outside the model on curved areas — the core issue still persists: travel moves are still crossing internal walls unnecessarily, even when Avoid Crossing Wall is enabled.
> 
> You can see this clearly in the screenshots attached. These crossings occur in situations where the path planner could clearly avoid them. What makes this especially problematic is when printing flexible materials like TPU, where clean travel paths really matter for quality as mentioned.
> 
> One additional detail: I’m using a custom seam setting, but the exact same configuration works perfectly in OrcaSlicer, and was previously handled correctly in older versions of Bambu Studio.
> 
> To summarize: • Bambu Studio 2.2.0 beta improves outer travel behavior on curves ✅ • Avoid Crossing Wall still doesn’t prevent unnecessary internal wall crossings ❌ • Custom seam settings may play a role, but it’s not an issue in OrcaSlicer or earlier Bambu Studio releases
> 
> Happy to share more info if needed — hoping this helps others or leads to further improvements!
> 
> ![Image](https://github.com/user-attachments/assets/5c79cec5-fc97-47e1-a284-e3ccc392c9b4) ![Image](https://github.com/user-attachments/assets/3d1f97fa-b8f7-473d-81c5-61a3e927865a)

Hi, thanks for your feedback. Please check if the travel through the walls is from one layer to the next layer. We have observed the issue and are actively discussing potential solutions. Meanwhile, we appreciate the efforts made by Orca in this area: https://github.com/SoftFever/OrcaSlicer/pull/10185. Thank you again for your valuable feedback, and we kindly ask for your patience as we work on upcoming fixes and improvements.

By the way, could you please package your 3MF file into a ZIP archive and upload it as an attachment?

**Comment by sakomoto987** [comment]
> > Hi everyone,
> > Just wanted to share some findings regarding the Avoid Crossing Wall feature in Bambu Studio, in case others are running into similar issues.
> > I’ve tested the recent 2.2.0 Public Beta, and while there are some improvements — notably, the nozzle no longer travels outside the model on curved areas — the core issue still persists: travel moves are still crossing internal walls unnecessarily, even when Avoid Crossing Wall is enabled.
> > You can see this clearly in the screenshots attached. These crossings occur in situations where the path planner could clearly avoid them. What makes this especially problematic is when printing flexible materials like TPU, where clean travel paths really matter for quality as mentioned.
> > One additional detail: I’m using a custom seam setting, but the exact same configuration works perfectly in OrcaSlicer, and was previously handled correctly in older versions of Bambu Studio.
> > To summarize: • Bambu Studio 2.2.0 beta improves outer travel behavior on curves ✅ • Avoid Crossing Wall still doesn’t prevent unnecessary internal wall crossings ❌ • Custom seam settings may play a role, but it’s not an issue in OrcaSlicer or earlier Bambu Studio releases
> > Happy to share more info if needed — hoping this helps others or leads to further improvements!
> > ![Image](https://github.com/user-attachments/assets/5c79cec5-fc97-47e1-a284-e3ccc392c9b4) ![Image](https://private-user-images.githubusercontent.com/33251081/468579036-3d1f97fa-b8f7-473d-81c5-61a3e927865a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTM3ODQ3MzcsIm5iZiI6MTc1Mzc4NDQzNywicGF0aCI6Ii8zMzI1MTA4MS80Njg1NzkwMzYtM2QxZjk3ZmEtYjhmNy00NzNkLTgxYzUtNjFhM2U5Mjc4NjVhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA3MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNzI5VDEwMjAzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkY2EwZWI1ZTcwN2EwZDZmYjUzOWFjMTQ0M2Q5ZGUxNmFiMjE1M2EzYmQ0MDI4MDk1MWQyN2Q1OWFhMGIwZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.0-Igzo4jczyAHRyQ7AXJmr-iGhltEjxBy7Th4YwuGtI)
> 
> Hi, thanks for your feedback. Please check if the travel through the walls is from one layer to the next layer. We have observed the issue and are actively discussing potential solutions. Meanwhile, we appreciate the efforts made by Orca in this area: [SoftFever/OrcaSlicer#10185](https://github.com/SoftFever/OrcaSlicer/pull/10185). Thank you again for your valuable feedback, and we kindly ask for your patience as we work on upcoming fixes and improvements.
> 
> By the way, could you please package your 3MF file into a ZIP archive and upload it as an attachment?

Thank you for your response. Here is a link to download the .3MF file with the models and the configuration inside. To answer you, I think this happens during the layer change.

**.3mf**
https://icedrive.net/s/8FTSkBjDvFBxD59yjChvhhTk4tXh

**Comment by sakomoto987** [comment]
@Intec-bambu 

Update:

After several weeks of testing Bambu Studio 2.2.0 Public Beta 1, I noticed an interesting outcome. While the slicer preview still showed unexpected travel moves from the nozzle (that Avoid Crossing Wall should ideally prevent), the actual printed results were surprisingly clean. The print quality in real life was acceptable and met my expectations, despite the previewed travel paths.

However, after about a week, I moved on to testing Bambu Studio 2.2.0 Public Beta 2, and the results changed drastically — and not for the better. Using exactly the same setup (same filament, same process configuration, same model), the print quality degraded significantly. The difference is visually obvious, and I’ll attach a photo showing the issue. In Beta 2, the print output is far below the standard of Beta 1.

To confirm, I reverted back to Beta 1, and the quality immediately returned to the acceptable level I had before, again with only the known issue of unnecessary travel paths remaining.

I cannot identify what changes were introduced between Beta 1 and Beta 2 that would explain this drastic drop in print quality, but it’s clear that something in the slicing or travel path planning logic has negatively impacted the output.

Summary of findings:
	•	Beta 1: Travel path preview still shows unnecessary moves, but real-world print quality is good/acceptable. As you can notice in attachment photo, stringing is still present even with the first beta where the nozzle travel outside the model, but acceptable at the moment..
	•	Beta 2: Same settings, filament, and model produce significantly worse results.
	•	Reverting to Beta 1 restores the quality.

@Intec-bambu — would be great to know if others are seeing similar differences between Beta 1 and Beta 2, and if there’s any insight into what changed in the travel/path planning between the two builds.

Thanks,
Brandon

![Image](https://github.com/user-attachments/assets/f4035237-f1ab-49c3-8c92-659472b95366)

**Comment by Intec-bambu** [comment]
> [@Intec-bambu](https://github.com/Intec-bambu)
> 
> Update:
> 
> After several weeks of testing Bambu Studio 2.2.0 Public Beta 1, I noticed an interesting outcome. While the slicer preview still showed unexpected travel moves from the nozzle (that Avoid Crossing Wall should ideally prevent), the actual printed results were surprisingly clean. The print quality in real life was acceptable and met my expectations, despite the previewed travel paths.
> 
> However, after about a week, I moved on to testing Bambu Studio 2.2.0 Public Beta 2, and the results changed drastically — and not for the better. Using exactly the same setup (same filament, same process configuration, same model), the print quality degraded significantly. The difference is visually obvious, and I’ll attach a photo showing the issue. In Beta 2, the print output is far below the standard of Beta 1.
> 
> To confirm, I reverted back to Beta 1, and the quality immediately returned to the acceptable level I had before, again with only the known issue of unnecessary travel paths remaining.
> 
> I cannot identify what changes were introduced between Beta 1 and Beta 2 that would explain this drastic drop in print quality, but it’s clear that something in the slicing or travel path planning logic has negatively impacted the output.
> 
> Summary of findings: • Beta 1: Travel path preview still shows unnecessary moves, but real-world print quality is good/acceptable. As you can notice in attachment photo, stringing is still present even with the first beta where the nozzle travel outside the model, but acceptable at the moment.. • Beta 2: Same settings, filament, and model produce significantly worse results. • Reverting to Beta 1 restores the quality.
> 
> [@Intec-bambu](https://github.com/Intec-bambu) — would be great to know if others are seeing similar differences between Beta 1 and Beta 2, and if there’s any insight into what changed in the travel/path planning between the two builds.
> 
> Thanks, Brandon
> 
> ![Image](https://github.com/user-attachments/assets/f4035237-f1ab-49c3-8c92-659472b95366)

The 'avoid crossing walls' feature has not been modified recently. However, there was a recent change related to Z-hop/retract that increases the frequency of nozzle lifts during travel to prevent collisions. I will analyze whether the TPU print quality degradation is related to this change, but my current task schedule is quite tight—please allow me some time.

By the way, reducing the Z-hop value might help minimize stringing with TPU. You can try setting Extruder->Z-hop when retract = 0 and observe if print quality improves. The underlying idea is that the nozzle attempts to wipe away oozing material across the layer surface as it moves, but this may increase the risk of collisions.

Thank you again for your valuable feedback!

**Comment by Intec-bambu** [comment]
> [@Intec-bambu](https://github.com/Intec-bambu)
> 
> Update:
> 
> After several weeks of testing Bambu Studio 2.2.0 Public Beta 1, I noticed an interesting outcome. While the slicer preview still showed unexpected travel moves from the nozzle (that Avoid Crossing Wall should ideally prevent), the actual printed results were surprisingly clean. The print quality in real life was acceptable and met my expectations, despite the previewed travel paths.
> 
> However, after about a week, I moved on to testing Bambu Studio 2.2.0 Public Beta 2, and the results changed drastically — and not for the better. Using exactly the same setup (same filament, same process configuration, same model), the print quality degraded significantly. The difference is visually obvious, and I’ll attach a photo showing the issue. In Beta 2, the print output is far below the standard of Beta 1.
> 
> To confirm, I reverted back to Beta 1, and the quality immediately returned to the acceptable level I had before, again with only the known issue of unnecessary travel paths remaining.
> 
> I cannot identify what changes were introduced between Beta 1 and Beta 2 that would explain this drastic drop in print quality, but it’s clear that something in the slicing or travel path planning logic has negatively impacted the output.
> 
> Summary of findings: • Beta 1: Travel path preview still shows unnecessary moves, but real-world print quality is good/acceptable. As you can notice in attachment photo, stringing is still present even with the first beta where the nozzle travel outside the model, but acceptable at the moment.. • Beta 2: Same settings, filament, and model produce significantly worse results. • Reverting to Beta 1 restores the quality.
> 
> [@Intec-bambu](https://github.com/Intec-bambu) — would be great to know if others are seeing similar differences between Beta 1 and Beta 2, and if there’s any insight into what changed in the travel/path planning between the two builds.
> 
> Thanks, Brandon
> 
> ![Image](https://github.com/user-attachments/assets/f4035237-f1ab-49c3-8c92-659472b95366)

Disabling timelapse photography might also be beneficial, as the travel paths during timelapse are entirely determined by custom G-code. When timelapse is enabled, the nozzle moves to a position that maintains an unobstructed camera view after printing each layer. This may introduce unnecessary travel moves across walls

**Comment by sakomoto987** [comment]
Thanks for the feedback.

Regarding the first point (reducing Z-hop to minimize stringing with TPU): in my current setup, the Extruder > Z-hop when retract value is set to “n/a” (not assigned), so it’s effectively disabled. I understand your suggestion about setting it explicitly to 0 to avoid unnecessary nozzle lifts, so I’ll run a test with that configuration to see if it changes anything.

As for the second point (disabling timelapse), I can confirm that timelapse photography was disabled in both test prints (Beta 1 and Beta 2), so that factor can be ruled out in this case.

I’ll follow up after testing with Z-hop explicitly set to 0. @Intec-bambu

**Comment by dynarun777** [comment]
For a long time, I worked with Bambu Studio 01.09.07.52 and had no problems avoiding walls. 
When I switched to 02.01.01.52, I noticed blobs on the exterior walls, and the rapid traverse paths changed. 
The nozzle took the path over the exterior wall and not through the interior walls as before. 
With the new version 02.02.00.85, the travel paths look correct again and smoother than 01.09.07.52 .

Thanks for fixing the bug!


![Image](https://github.com/user-attachments/assets/20743788-7f35-467c-a9f6-20c1c5420d0b)

![Image](https://github.com/user-attachments/assets/8a4e45e6-e522-4443-bbbb-28e479d4f938)

**Comment by daygp** [comment]
Have just installed version 2.2.0.85 and are experiencing the issues described above.

For me, the problem appears to occur when the infill on a layer has been completed and the nozzle returns to the start point of the next layer.  During the infill process, avoid crossing walls is respected so it appears to only occur during the transition between layers. 

FYI, I have retraction set to zero for LW-PLA.

Image shows avoid crossing walls being respected during infill process.

<img width="471" height="468" alt="Image" src="https://github.com/user-attachments/assets/3a3a9edc-b0e6-4f4a-99c1-d18448cd9907" />

Image shows the path as the nozzle returns to the layer start point

<img width="1416" height="428" alt="Image" src="https://github.com/user-attachments/assets/36ae0bcd-2143-4a51-8f80-32a0bfbbecfc" />

**Comment by nerdcraft-muc** [comment]
I don't know if this information is helpful. I have the same issue when I export an object as *.amf from FreeCAD (0.21.1), but it is completely gone if I do the meshing in FreeCAD and export the object as *.stl!

<img width="643" height="648" alt="Image" src="https://github.com/user-attachments/assets/4898d6b7-0725-43d7-a85b-7d9c68a739db" />

Meshed in FreeCAD

<img width="625" height="590" alt="Image" src="https://github.com/user-attachments/assets/07c60a9f-ad2b-4ffc-b3eb-681ecd05348e" />

Exported as *.amf

**Comment by Zirkowa** [comment]
Hey there, I'm new to Github and the fact that I don't know anything about coding and still talking to you shows how desperate I am.

For months now I'm trying to print a special object and I tried every possible option, settings combinations, filament drying. Nothing helps me resolve the issue.

I used Orca as well to prove myself that it's not my fault and yes, same result.

I wanted to show you that even if the simulation shows no wall crossing what so ever, the printer DOES it. I'm hopeful now because I've seen that you talked about that bug before.

<img width="1762" height="1666" alt="Image" src="https://github.com/user-attachments/assets/33ed7bee-aa7e-44a1-9bb9-9c96270dbf45" />

The red line shows the actual path the nozzle is going.

![Image](https://github.com/user-attachments/assets/6b5ffbe6-c9cc-49a2-81d4-4bd4eeb24428)

The print result is really poor.

There is the gcode if you need it. https://we.tl/t-ufx2gNyYAU

Do you need anything from me that might be helpful?


Regards,
Zirkowa

**Comment by Intec-bambu** [comment]
> Have just installed version 2.2.0.85 and are experiencing the issues described above.刚刚安装了 2.2.0.85 版本，正在遇到上面描述的问题。
> 
> For me, the problem appears to occur when the infill on a layer has been completed and the nozzle returns to the start point of the next layer. During the infill process, avoid crossing walls is respected so it appears to only occur during the transition between layers.对我来说，这个问题似乎发生在某一层的填充完成后喷嘴返回到下一层起点的时候。在填充过程中，“Avoid Crossing Walls”会被遵守，所以这个问题似乎只发生在层与层之间的过渡阶段。
> 
> FYI, I have retraction set to zero for LW-PLA.供参考，我已将 LW-PLA 的回抽设为零。
> 
> Image shows avoid crossing walls being respected during infill process.图片显示“避免穿墙”在填充过程中被遵守。
> 
> <img alt="Image" width="471" height="468" src="https://private-user-images.githubusercontent.com/103159749/478820160-3a3a9edc-b0e6-4f4a-99c1-d18448cd9907.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTYxNzI0MTUsIm5iZiI6MTc1NjE3MjExNSwicGF0aCI6Ii8xMDMxNTk3NDkvNDc4ODIwMTYwLTNhM2E5ZWRjLWIwZTYtNGY0YS05OWMxLWQxODQ0OGNkOTkwNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwODI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDgyNlQwMTM1MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02M2YwZDQ4ZjYzZDZhNTY4NjQxMmRjZjQ0MjIxZTFlOWY2NmYyNzQwZTllMWZmMjQwM2U0OTU1NzA4OGJkOGM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.t4TF6xsz9tJimN_L-CfFKXbstXMQxC_lZgiv9mfL_pA">
> Image shows the path as the nozzle returns to the layer start point图片显示了喷嘴返回到图层起点时的路径
> 
> <img alt="Image" width="1416" height="428" src="https://private-user-images.githubusercontent.com/103159749/478819699-36ae0bcd-2143-4a51-8f80-32a0bfbbecfc.PNG?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTYxNzI0MTUsIm5iZiI6MTc1NjE3MjExNSwicGF0aCI6Ii8xMDMxNTk3NDkvNDc4ODE5Njk5LTM2YWUwYmNkLTIxNDMtNGE1MS04ZjgwLTMyYTBiZmJiZWNmYy5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwODI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDgyNlQwMTM1MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kOWFhYTBkNmJjZjRjMmUwYWIyMzhjN2E2NTA1MGU3ODBiNTU4MGQ0YWM5YmYzZDYzZTYzMTUyNDhmNDNkNTg5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.8e6oJhKFUsVOG_CRdM0YxLmOgWoEZfcF2KV4llOJnHo">

This is a known issue, thank you for your feedback! Could you please package your 3MF file or other format model files into a ZIP archive and upload it as an attachment? This will help us expand our model testing dataset

**Comment by Intec-bambu** [comment]
> I don't know if this information is helpful. I have the same issue when I export an object as *.amf from FreeCAD (0.21.1), but it is completely gone if I do the meshing in FreeCAD and export the object as *.stl!我不知道这些信息是否有帮助。我在从 FreeCAD (0.21.1) 将对象导出为 *.amf 时也遇到相同的问题，但如果我在 FreeCAD 中进行网格化并将对象导出为 *.stl，这个问题就完全消失了！
> 
> <img alt="Image" width="643" height="648" src="https://private-user-images.githubusercontent.com/95968772/481365616-4898d6b7-0725-43d7-a85b-7d9c68a739db.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTYxNzI2MjcsIm5iZiI6MTc1NjE3MjMyNywicGF0aCI6Ii85NTk2ODc3Mi80ODEzNjU2MTYtNDg5OGQ2YjctMDcyNS00M2Q3LWE4NWItN2Q5YzY4YTczOWRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwODI2VDAxMzg0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwMjIyZWMzYWQzM2RhY2VmMGI3YjE3OGVjNDQ0YTY0Y2M2ZjNmM2UxOGIzZmNmN2YwMWRiOTc4MzNkZjc1NGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.2Wv3lwWHfKu8obuR-AsZa--V0RmlpjqH5bxMoDiv2uk">
> Meshed in FreeCAD  在 FreeCAD 中网格化
> 
> <img alt="Image" width="625" height="590" src="https://private-user-images.githubusercontent.com/95968772/481365621-07c60a9f-ad2b-4ffc-b3eb-681ecd05348e.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTYxNzI2MjcsIm5iZiI6MTc1NjE3MjMyNywicGF0aCI6Ii85NTk2ODc3Mi80ODEzNjU2MjEtMDdjNjBhOWYtYWQyYi00ZmZjLWIzZWItNjgxZWNkMDUzNDhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwODI2VDAxMzg0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzZDBkOTkxZjE4NDNhN2ZkYmI1MTA1MTAzNDc0Mzg3NjU0YzQzYzljNDI2YTc2N2QxMGI1MWUxNmY3YTc1MTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.2z9lVAULFyFXW8PVsJx1GEFqJiKk_EvIXAnAfR44oOM">
> Exported as *.amf  已导出为 *.amf

Could you please package your amf and stl files into a ZIP archive and upload it as an attachment?

**Comment by Intec-bambu** [comment]
> Hey there, I'm new to Github and the fact that I don't know anything about coding and still talking to you shows how desperate I am.嗨，我是 GitHub 新手，而且我不会写代码，还来跟你们说话，这就说明我有多着急了。
> 
> For months now I'm trying to print a special object and I tried every possible option, settings combinations, filament drying. Nothing helps me resolve the issue.几个月来我一直在尝试打印一个特殊对象，尝试了所有可能的选项、设置组合和干燥耗材。没有任何办法能解决这个问题。
> 
> I used Orca as well to prove myself that it's not my fault and yes, same result.我也用过 Orca 来证明这不是我的错，结果也是一样。
> 
> I wanted to show you that even if the simulation shows no wall crossing what so ever, the printer DOES it. I'm hopeful now because I've seen that you talked about that bug before.我想向你展示，即使仿真显示完全没有穿墙，打印机还是会穿墙。我现在有些希望，因为我看到你之前讨论过那个漏洞。
> 
> <img alt="Image" width="1762" height="1666" src="https://private-user-images.githubusercontent.com/228377103/481766041-33ed7bee-aa7e-44a1-9bb9-9c96270dbf45.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTYxNzI5MDcsIm5iZiI6MTc1NjE3MjYwNywicGF0aCI6Ii8yMjgzNzcxMDMvNDgxNzY2MDQxLTMzZWQ3YmVlLWFhN2UtNDRhMS05YmI5LTljOTYyNzBkYmY0NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwODI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDgyNlQwMTQzMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYmI4YmQxYzQxMmFhYmQ1MmNkYjZhZWNmMDk3ZDg1OTY4ZDZjNzM4NDdhZDYwMzRjYmM5ODIyOThjYmZmYjkzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Bys1DtdtnOiC8mHJCGpEYGNMW75b3j7BFzzRF7jUpWk">
> The red line shows the actual path the nozzle is going.红线显示喷嘴实际移动的路径。
> 
> ![Image](https://github.com/user-attachments/assets/6b5ffbe6-c9cc-49a2-81d4-4bd4eeb24428)
> 
> The print result is really poor.打印结果非常糟糕。
> 
> There is the gcode if you need it. https://we.tl/t-ufx2gNyYAU如果需要，这是 gcode。https://we.tl/t-ufx2gNyYAU
> 
> Do you need anything from me that might be helpful?你还需要我提供什么可能有帮助的信息吗？
> 
> Regards,  此致， Zirkowa

Could you please package your 3MF file or other format model files, such as stl, obj, etc., into a ZIP archive and upload it as an attachment？

**Comment by nerdcraft-muc** [comment]
> > I don't know if this information is helpful. I have the same issue when I export an object as *.amf from FreeCAD (0.21.1), but it is completely gone if I do the meshing in FreeCAD and export the object as *.stl!我不知道这些信息是否有帮助。我在从 FreeCAD (0.21.1) 将对象导出为 *.amf 时也遇到相同的问题，但如果我在 FreeCAD 中进行网格化并将对象导出为 *.stl，这个问题就完全消失了！
> > <img alt="Image" width="643" height="648" src="https://private-user-images.githubusercontent.com/95968772/481365616-4898d6b7-0725-43d7-a85b-7d9c68a739db.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTYxNzI2MjcsIm5iZiI6MTc1NjE3MjMyNywicGF0aCI6Ii85NTk2ODc3Mi80ODEzNjU2MTYtNDg5OGQ2YjctMDcyNS00M2Q3LWE4NWItN2Q5YzY4YTczOWRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwODI2VDAxMzg0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwMjIyZWMzYWQzM2RhY2VmMGI3YjE3OGVjNDQ0YTY0Y2M2ZjNmM2UxOGIzZmNmN2YwMWRiOTc4MzNkZjc1NGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.2Wv3lwWHfKu8obuR-AsZa--V0RmlpjqH5bxMoDiv2uk">
> > Meshed in FreeCAD  在 FreeCAD 中网格化
> > <img alt="Image" width="625" height="590" src="https://private-user-images.githubusercontent.com/95968772/481365621-07c60a9f-ad2b-4ffc-b3eb-681ecd05348e.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTYxNzI2MjcsIm5iZiI6MTc1NjE3MjMyNywicGF0aCI6Ii85NTk2ODc3Mi80ODEzNjU2MjEtMDdjNjBhOWYtYWQyYi00ZmZjLWIzZWItNjgxZWNkMDUzNDhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwODI2VDAxMzg0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzZDBkOTkxZjE4NDNhN2ZkYmI1MTA1MTAzNDc0Mzg3NjU0YzQzYzljNDI2YTc2N2QxMGI1MWUxNmY3YTc1MTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.2z9lVAULFyFXW8PVsJx1GEFqJiKk_EvIXAnAfR44oOM">
> > Exported as *.amf  已导出为 *.amf
> 
> Could you please package your amf and stl files into a ZIP archive and upload it as an attachment?

[DE_VOIGT_10MM-Body.zip](https://github.com/user-attachments/files/21983740/DE_VOIGT_10MM-Body.zip)

**Comment by Zirkowa** [comment]
> >...
> 
> Could you please package your 3MF file or other format model files, such as stl, obj, etc., into a ZIP archive and upload it as an attachment?

Of course I can.

[stl + 3mf.zip](https://github.com/user-attachments/files/22012252/stl.%2B.3mf.zip)

Thank you very much for your effort!

Regards

**Comment by dkbay** [comment]
Weirdly this doesn't seem to affect A1 printers.

Screenshot shows same avoid crossing settings and roughly same settings other than that.
But on the X1C bambu studio doesn't respect it while it looks fine on the A1.
<img width="1512" height="946" alt="Image" src="https://github.com/user-attachments/assets/05da7061-878a-48bd-9021-a22a19f770b8" />

X1C in orca for reference

<img width="710" height="765" alt="Image" src="https://github.com/user-attachments/assets/dadc0d25-8cb2-4e18-845d-5f14477faf09" />

**Comment by Zirkowa** [comment]
Interesting. My case shows results from the A1. Terrible bug this is.
Luckily, I found a way to get almost perfect prints now.

**Comment by dkbay** [comment]
> For a long time, I worked with Bambu Studio 01.09.07.52 and had no problems avoiding walls. When I switched to 02.01.01.52, I noticed blobs on the exterior walls, and the rapid traverse paths changed. The nozzle took the path over the exterior wall and not through the interior walls as before. With the new version 02.02.00.85, the travel paths look correct again and smoother than 01.09.07.52 .
> 
> Thanks for fixing the bug!
> 
> ![Image](https://github.com/user-attachments/assets/20743788-7f35-467c-a9f6-20c1c5420d0b)
> 
> ![Image](https://github.com/user-attachments/assets/8a4e45e6-e522-4443-bbbb-28e479d4f938)

I still have the issue on 2.2.2.56

**Comment by Zirkowa** [comment]
I highly recommend to test the simulation afterwards. Look at my previous post. Bambu Studio shows perfect travelling but the actually printed result proofs that the problem is still there.

Okay, I got to check the latest version if the issue still occurs. But I doubt it.

It's by the way also existent in Orca Slicer.

Greetings!

**Comment by Intec-bambu** [comment]
> I highly recommend to test the simulation afterwards. Look at my previous post. Bambu Studio shows perfect travelling but the actually printed result proofs that the problem is still there.
> 
> Okay, I got to check the latest version if the issue still occurs. But I doubt it.
> 
> It's by the way also existent in Orca Slicer.
> 
> Greetings!

Thanks for your feedback. I will try to review and optimize it.

**Comment by BoBoYu-BamBu** [comment]
Thank you for your feedback. This issue has been fixed. Please update to the latest version of Studio for verification. Download link: https://bambulab.cn/zh-cn/download/studio

**Comment by RafaelEufrazio** [comment]
I'm still having this issue with the latest version. Any idea what may be happening here?

Please let me know if I'm missing something.

<img width="1916" height="1029" alt="Image" src="https://github.com/user-attachments/assets/d4475bcd-b5ce-4db8-bf19-cb3c8e0f96a3" />

**Comment by BoBoYu-BamBu** [comment]
@RafaelEufrazio Could you please provide the 3mf file?

**Comment by RafaelEufrazio** [comment]
Sure how do I send it to you? Seems like github doesn't support .3mf files

**Comment by BoBoYu-BamBu** [comment]
You can send it to my email: yuting.huang@bambulab.com

**Comment by RafaelEufrazio** [comment]
Just sent it.

**Comment by BoBoYu-BamBu** [comment]
Received. Thank you. We will conduct the analysis.

**Comment by grumpypotato-bambu** [comment]
> I'm still having this issue with the latest version. Any idea what may be happening here?
> 
> Please let me know if I'm missing something.
> 
> <img alt="Image" width="1916" height="1029" src="https://private-user-images.githubusercontent.com/73612516/523330290-d4475bcd-b5ce-4db8-bf19-cb3c8e0f96a3.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjUxOTUzNzcsIm5iZiI6MTc2NTE5NTA3NywicGF0aCI6Ii83MzYxMjUxNi81MjMzMzAyOTAtZDQ0NzViY2QtYjVjZS00ZGI4LWJmMTktY2IzYzhlMGY5NmEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMjA4VDExNTc1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwMjVhZmJmNjdkMWM1MDk1OTRkN2ZjNGMzMWMyYmMzOTgxMDMxMDlmYWQ5NDI2OGI2OGVhZGMwNTQxYzNlNDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.K9vUh6w6SlvyJIpnFi2HGHOIppAhRwWlfapFf92KbOw">

Hi, thank you for your feedback. I have looked into this issue and it's actually working as intended. The travel paths in the image are generated such that the extruder stays in a fixed position in a timelapse video, and if you print with timelapse turned off these travels won't actually be executed.

**Comment by RafaelEufrazio** [comment]
> Hi, thank you for your feedback. I have looked into this issue and it's actually working as intended. The travel paths in the image are generated such that the extruder stays in a fixed position in a timelapse video, and if you print with timelapse turned off these travels won't actually be executed.

Is there any way to not see the travel lines of the timelapse into the slice preview? I'm not intending to run a timelapse.

**Comment by grumpypotato-bambu** [comment]
> > Hi, thank you for your feedback. I have looked into this issue and it's actually working as intended. The travel paths in the image are generated such that the extruder stays in a fixed position in a timelapse video, and if you print with timelapse turned off these travels won't actually be executed.
> 
> Is there any way to not see the travel lines of the timelapse into the slice preview? I'm not intending to run a timelapse.

Currently there is no way to turn this off in the preview without affecting the resulting gcode, unfortunately. You can delete the timelapse gcode in the printer settings to prevent these travels from being generated in the first place:

<img width="1102" height="870" alt="Image" src="https://github.com/user-attachments/assets/94e653af-0924-42f0-b114-da2936ddbd66" />

However, the head wrap detection functionality is tightly coupled with this setting. If you do delete the timelapse gcode, you run the risk of not detecting potential head wraps, and therefore potential damage to the machine.

**Comment by RafaelEufrazio** [comment]
> Currently there is no way to turn this off in the preview without affecting the resulting gcode, unfortunately. You can delete the timelapse gcode in the printer settings to prevent these travels from being generated in the first place:
> 
> <img width="1102" height="870" alt="Image" src="https://github.com/user-attachments/assets/94e653af-0924-42f0-b114-da2936ddbd66" />
> 
> However, the head wrap detection functionality is tightly coupled with this setting. If you do delete the timelapse gcode, you run the risk of not detecting potential head wraps, and therefore potential damage to the machine.

Gotcha. I hope there's a better way to deal with this in the future, maybe somehow decoupling the timelapse gcode or something else.

Although misleading, now that I know what to look for I think this won't be a problem, thanks!

**Comment by hyt589** [comment]
> > Currently there is no way to turn this off in the preview without affecting the resulting gcode, unfortunately. You can delete the timelapse gcode in the printer settings to prevent these travels from being generated in the first place:
> > <img alt="Image" width="1102" height="870" src="https://private-user-images.githubusercontent.com/248386316/524031227-94e653af-0924-42f0-b114-da2936ddbd66.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjUyNTAyMTksIm5iZiI6MTc2NTI0OTkxOSwicGF0aCI6Ii8yNDgzODYzMTYvNTI0MDMxMjI3LTk0ZTY1M2FmLTA5MjQtNDJmMC1iMTE0LWRhMjkzNmRkYmQ2Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTIwOVQwMzExNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xOWY4Nzc3ZjVlMWZjNTVkMGIyNjM4Njk4ZDE3ZTI0YmZmYWU5MmQwYzc2YTkwZDM1YjZlOWFjZGIyMWJhNTQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.nUPxzB1uuZCP0TNxQt42-hjIviViVAsEANvkDCLYv_Y">
> > However, the head wrap detection functionality is tightly coupled with this setting. If you do delete the timelapse gcode, you run the risk of not detecting potential head wraps, and therefore potential damage to the machine.
> 
> Gotcha. I hope there's a better way to deal with this in the future, maybe somehow decoupling the timelapse gcode or something else.
> 
> Although misleading, now that I know what to look for I think this won't be a problem, thanks!

Glad to help. Also thanks for you feedback, we will look into ways to improve the UX.

Closing as this is not a bug.
