### ISSUE TITLE
Bambu studio for Mac crashes if I leave it running and put my machine to sleep

### ISSUE THREAD

**Issue by neilcsinger** [bambulab/BambuStudio#7291]
### Bambu Studio Version

2.1.0.59

### Where is the application from?

Bambu Lab Official website

### OS version

macOS 15.5

### Additional system information

MacBook Pro, Apple M4 Pro, 48 GB

### Printer

Bambu Labs P1P

### How to reproduce

Bug started with latest update.  It never happened before.
1. Print with bambu studio
2. wait for download and printer to start
3. put Mac to sleep by closing its cover
4. open Mac and Bambu Studio is crashed

### Actual results

Bambu Studio crashes

### Expected results

It should still be running (as in the previous versions)

### Project file & Debug log uploads

[Outer Wheel 2.3mf.zip](https://github.com/user-attachments/files/20749984/Outer.Wheel.2.3mf.zip)
[log files.zip](https://github.com/user-attachments/files/20749983/log.files.zip)

### Checklist of files to include

- [x] Log file
- [x] Project file

**Comment by BoBoYu-BamBu** [comment]
@neilcsinger  Thank you for your feedback. We have already fixed this issue and released a new plugin: V2.1.0.56. Please update the plugin and try again.

**Comment by AndriyDmytrenko** [comment]
Still reproduces for me.
Bambu Studio 2.1.1.52

**Comment by perlbo** [comment]
Same here. New plugin does not solve the problem

**Comment by neilcsinger** [comment]
Yes. It still crashes for me as well. V2.1.1.52

**Comment by TinyMito** [comment]
> [@neilcsinger](https://github.com/neilcsinger) Thank you for your feedback. We have already fixed this issue and released a new plugin: V2.1.0.56. Please update the plugin and try again.

How do I verify if I have the latest plugin? I have ran check for updates, nothing shows up and I assume I am already on the latest version. It is still crashing.

**Comment by XinZhangBambu** [comment]
@TinyMito @neilcsinger  @perlbo @AndriyDmytrenko, Thank you for your feedback. Could you please copy and paste the crash report of MAC for us.

**Comment by perlbo** [comment]
> [@TinyMito](https://github.com/TinyMito) [@neilcsinger](https://github.com/neilcsinger) [@perlbo](https://github.com/perlbo) [@AndriyDmytrenko](https://github.com/AndriyDmytrenko), Thank you for your feedback. Could you please copy and paste the crash report of MAC for us.

[crashj report.pdf](https://github.com/user-attachments/files/20894216/crashj.report.pdf)

**Comment by perlbo** [comment]
> [@TinyMito](https://github.com/TinyMito) [@neilcsinger](https://github.com/neilcsinger) [@perlbo](https://github.com/perlbo) [@AndriyDmytrenko](https://github.com/AndriyDmytrenko), Thank you for your feedback. Could you please copy and paste the crash report of MAC for us.

[crashj report.odt](https://github.com/user-attachments/files/20896291/crashj.report.odt)

**Comment by XinZhangBambu** [comment]
@perlbo Thank you.  From the report, i recognize that the process freezed not crashed. Is that true?

![Image](https://github.com/user-attachments/assets/73d1e8eb-fd96-46e2-a306-c17efbd30faf)

**Comment by perlbo** [comment]
Yes. Before the Network update it Crashs. Now it freeze.

**Comment by FyrbyAdditive** [comment]
I also have this problem, same spec/OS version as the OP. It crashes reliably every night without fail.

**Comment by XinZhangBambu** [comment]
@perlbo Thank you for your feedback. Your issue will be fixed on next plugin version.
@FyrbyAdditive @neilcsinger @AndriyDmytrenko @TinyMito  Could you please copy and paste the crash or freeze report of MAC for us.

**Comment by TinyMito** [comment]
> [@perlbo](https://github.com/perlbo) Thank you for your feedback. Your issue will be fixed on next plugin version. [@FyrbyAdditive](https://github.com/FyrbyAdditive) [@neilcsinger](https://github.com/neilcsinger) [@AndriyDmytrenko](https://github.com/AndriyDmytrenko) [@TinyMito](https://github.com/TinyMito) Could you please copy and paste the crash or freeze report of MAC for us.

Found out the pattern, my MacBook Pro M1 Pro is connected to external monitor (don't know if that factors in) but at night I leave my Bambu Studio up running then I close the lid. Next morning, I open the lid and login, the Bambu Studio just shows up a crash report that will be sent to Apple.

**CRASH LOG FILE HERE: [crash-log.txt](https://github.com/user-attachments/files/20924431/crash-log.txt)**

![Image](https://github.com/user-attachments/assets/871c3c73-509a-4cb6-93d8-0ceac091132a)

**Comment by XinZhangBambu** [comment]
@TinyMito Thank you for your feedback. We have fixed the problem, and the fixed version will be published at next release of Bambu Studio

**Comment by FyrbyAdditive** [comment]
Sorry for the delay. Here it is:

[bbs crash.txt](https://github.com/user-attachments/files/21015525/bbs.crash.txt)

**Comment by XinZhangBambu** [comment]
@FyrbyAdditive  Thank you for your feedback.  We have fixed the problem shown in bbs_crash.txt, and the fixed version will be published at next release of Bambu Studio

> Sorry for the delay. Here it is:
> 
> [bbs crash.txt](https://github.com/user-attachments/files/21015525/bbs.crash.txt)

**Comment by XinZhangBambu** [comment]
Halo, we have solved the problem at latest release. please check https://github.com/bambulab/BambuStudio/tags

<img width="970" height="412" alt="Image" src="https://github.com/user-attachments/assets/46bad56f-0202-4327-b5a1-2223b85fa017" />

**Comment by dpkg** [comment]
Still hangs or crashes when coming back from sleep. Mostly it just hands and then i have to do force quite to run it again. 

MacOS 15.5
Bambu Studio 2.1.1.52 (latest)

**Comment by XinZhangBambu** [comment]
@dpkg This problem has been fixed since https://github.com/bambulab/BambuStudio/releases/tag/v02.02.00.60

> Still hangs or crashes when coming back from sleep. Mostly it just hands and then i have to do force quite to run it again.
> 
> MacOS 15.5 Bambu Studio 2.1.1.52 (latest)

**Comment by Plastdroid** [comment]
Issue persists as of v.02.2.2.56 , intel mac. Sequoia 15.6.1

**Comment by XinZhangBambu** [comment]
@Plastdroid Thank you for your feedback.  can you offer a log and dmp file for us, you can refer to https://wiki.bambulab.com/en/bambu-studio/troubleshoot/crash-freeze-issue to get your log and dmp file.

**Comment by timmead** [comment]
Still persisting with v2.2.2.56 on an Intel Mac on Sonoma 14.6.1. Happens every time the machine goes to sleep. No crash dump is available as it freezes rather than crashing, requiring a Force Quit.

**Comment by XinZhangBambu** [comment]
@timmead Thank you for your feedback. Could you please offer the sample file on Mac.

When a Mac application freezes, here's how to take a sample of the software:  

1. Open "Activity Monitor" (you can find it via Spotlight by pressing `Command + Space`, then typing "Activity Monitor" and hitting Enter).  
2. In the Activity Monitor window, locate the frozen application from the list (you can use the search bar in the top-right corner to quickly find it).  
3. Select the frozen application, then click the gear icon (action button) in the toolbar at the top of the window.  
4. From the dropdown menu, choose "Sample Process".  
5. A new window will appear showing the sampling progress. Wait for the process to complete (this may take a few seconds to a minute, depending on the application).  
6. Once sampling is finished, you can save the report by clicking "Save" in the sample window, which will generate a text file with detailed process information for debugging.  

This sample report contains information about the application's current thread status and function calls, which is helpful for analyzing why the software is unresponsive.

**Comment by timmead** [comment]
Thanks for the detailed instructions! Report attached below.

[bambu-studio-2-2-2-56-intel-mac-freeze-report.txt](https://github.com/user-attachments/files/22541449/bambu-studio-2-2-2-56-intel-mac-freeze-report.txt)

**Comment by timmead** [comment]
Hi @XinZhangBambu! Do you have any updates to share on this issue? It still happens consistently for me; Bambu freezes almost every time I come back to the computer.

**Comment by XinZhangBambu** [comment]
I'm sorry for not noticing your reply. The possible cause of this freeze is that the software is performing network operations when waking up, but the network connection hasn't been restored at that moment. You can try configuring your Mac to keep the network card active during sleep. Since this issue is quite different from the existing one, could you create a new issue to report this freezing problem? We will do our best to fix it in the next or the one after next release.


> Hi [@XinZhangBambu](https://github.com/XinZhangBambu)! Do you have any updates to share on this issue? It still happens consistently for me; Bambu freezes almost every time I come back to the computer.

**Comment by BoBoYu-BamBu** [comment]
Thank you for your feedback. This issue has been fixed. Please update to the latest version of Studio for verification. Download link: https://bambulab.cn/zh-cn/download/studio

**Comment by stoney66** [comment]
I'm running latest 2.4.0.70 and the issue still happens for me. MacOS 15.5

**Comment by timmead** [comment]
Yeah, it still happens for me too.

**Comment by pay191** [comment]
Latest Version for me - Still Crashes every time my mac goes to sleep, and then I wake it, Bambu Studio is frozen and i need to force quit it and re-open it.
