### ISSUE TITLE
"Failed to connect to server" after sleep

### ISSUE THREAD

**Issue by MarkusvonStaden** [bambulab/BambuStudio#7387]
### Bambu Studio Version

2.1.1.52

### Where is the application from?

Bambu Lab Official website

### OS version

macOS Sequoia

### Additional system information

M2 Max

### Printer

X1

### How to reproduce

1. Open Bambu Studio
2. Wait for mac to go to sleep
3. wake up mac
4. cry

### Actual results

Connection lost, Nothing helps. Have to restart Bambu studio. Extremly annoying

### Expected results

Just reconnect. Maybe press a button to reconnect, but this is absolutly annoying

### Project file & Debug log uploads

[log.zip](https://github.com/user-attachments/files/20889331/log.zip)

### Checklist of files to include

- [x] Log file
- [ ] Project file

**Comment by mean-ui-thread** [comment]
Same exact problem also happens on Linux:

### Bambu Studio Version
- 2.1.1.56

### Where is the application from?
- [Bambu_Studio_ubuntu-24.04_PR-8184.AppImage](https://github.com/bambulab/BambuStudio/releases/download/v02.02.02.56/Bambu_Studio_ubuntu-24.04_PR-8184.AppImage)

### OS version
- Debian 13.1 (Trixie)
- Linux Kernel 6.12.48+deb13-amd64

### Additional system information
- AMD 5800X3D
- B550 Chipset
- 32GB RAM

### Printer
P1S

### How to reproduce
1. Open Bambu Studio
2. Wait for linux to go to sleep
3. wake up linux
4. cry

### Actual results
Connection lost, Nothing helps. Have to restart Bambu studio. Extremly annoying

### Expected results
In my opinion, it should automatically reconnect

**Comment by BoBoYu-BamBu** [comment]
Thank you for your feedback. This issue has been fixed. Please update to the latest version of Studio for verification. Download link: https://bambulab.cn/zh-cn/download/studio

**Comment by mean-ui-thread** [comment]
Thank you @BoBoYu-BamBu

**Comment by mean-ui-thread** [comment]
Still happening on Linux: 

<img width="600" height="544" alt="Image" src="https://github.com/user-attachments/assets/c350787a-cc8c-419b-a9a4-6cbc10e2c9c8" />

<img width="617" height="696" alt="Image" src="https://github.com/user-attachments/assets/8bce87be-da4e-4e89-8818-2a00c26cc0c6" />

However, it looks like it eventually reconnects on its own after a minute or so.

**Comment by mean-ui-thread** [comment]
Didn't hear any response. Should we re-open this issue?
