### ISSUE TITLE
Cloudfalre Verify Human Infinite Loop

### ISSUE THREAD

**Issue by arejaybee** [bambulab/BambuStudio#7477]
### Bambu Studio Version

2.1.1.52

### Where is the application from?

Built from source by yourself or others

### OS version

PopOS

### Printer

Bambu Lab P1S

### How to reproduce

    1. Launch Bambu Labs
    2. Click Online Models, Click MakerLab, or search anything from Home page
    3. The makerworld.com page is displayed asking the user to verify they are human
    4. 

https://github.com/user-attachments/assets/6dc975b5-3b5c-4e28-b093-f11e6519ac84

User clicks the Verify you are human checkbox

### Actual results

    1. The spinner loads for a while
    2. Then the box refreshes to verify you are human
    3. No matter how many times the user clicks this, they are never verified
    4. The application is genuinely unusable as this locks the user out of all features

### Expected results

The user is verified and navigates to the page

### Project file & Debug log uploads

[log.zip](https://github.com/user-attachments/files/21071597/log.zip)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by arejaybee** [comment]
This issue presented itself a couple months ago - https://github.com/bambulab/BambuStudio/issues/6809
It was resolved for a short time, but the cloudflare validation seems to be broken again

**Comment by nanoprogrameur** [comment]
Happening for me again using flatpak on Linux Manjaro. It's working with Vivaldi browser.

**Comment by coyoteran** [comment]
Started happening yesterday for me as well. Not a solution but the appimage works for me. (Ubuntu 24.04.2 LTS)

**Comment by CLandsberg** [comment]
+1 with flatpack on endeavourOS

**Comment by kevintully** [comment]
I'm seeing the same behavior using the flatpak (V 2.1.1.52) on Ubuntu 24.04.2 LTS. I am not using a VPN and can visit Makerworkd on a web browser using the same host without a Cloudflare challenge. A macOS device on the same network, also on V 2.1.1.52, can load the Online Models tab and browse content without any issues.

**Comment by ant1fact** [comment]
+1 here

Bambu Studio version: 2.1.1.52 via Flatpak

OS:
Distributor ID:	Pop
Description:	Pop!_OS 22.04 LTS
Release:	22.04
Codename:	jammy

**Comment by frank-pian** [comment]
Sorry, there was a firewall issue. Has it been resolved now?

**Comment by jescanellas** [comment]
I still experience it, @frank-pian. 

Bambu Studio v2.1.1.52 via Flatpak

I'm on Linux Mint 22.1

**Comment by ant1fact** [comment]
Just tested again, issue persists

**Comment by kevintully** [comment]
Thanks for the update, @frank-pian. Unfortunately, there has been no change in the behavior, and the flatpak still exhibits a Cloudflare challenge loop.

**Comment by Seagull50** [comment]
I have the same issue.

Bambu Studio version : 2.1.1.52
OS: Linux Mint 22.1 Cinnamon

**Comment by rletendu** [comment]
Looks like this is now working again starting from yesterday, same BambuSutdio 2.1.1.52 flat pack  and Linux Mint 22.1 ...
