### ISSUE TITLE
Flow Calibration option missing on A1 Mini

### ISSUE THREAD

**Issue by Stagecoachsi** [bambulab/BambuStudio#7495]
### Bambu Studio Version

2.1.1.52

### Where is the application from?

Bambu Lab Official website

### OS version

Win 10

### Printer

Bambu Lab A1 mini

### How to reproduce

Al mini with [.2mm] nozzle, any setting will not let you perform a Flow calibration before sending the print. 

![Image](https://github.com/user-attachments/assets/73d5c45e-4307-4eb9-8b52-608e85728040)

### Actual results

Al mini with [.2mm] nozzle, any setting will not let you perform a Flow calibration before sending the print. 

### Expected results

Al mini with [.2mm] nozzle, Should let you perform a Flow calibration before sending the print. 

### Project file & Debug log uploads

[log.zip](https://github.com/user-attachments/files/21090919/log.zip)
[B14R Bottom Plate v5.zip](https://github.com/user-attachments/files/21090918/B14R.Bottom.Plate.v5.zip)

### Checklist of files to include

- [x] Log file
- [x] Project file

**Comment by aschubert** [comment]
Same here on Mac OS, A1 Mini 0.4mm nozzle. Reverted back to V2.0.3.54, callibration option available again.

**Comment by fahaaaxiki** [comment]
Please upload log through Handy APP, and give us your ticket number

Upload log files through Bambu Handy
Log files from the Bambu printer can be uploaded via Bambu Handy over the network, with an upload speed of around 150 kbps under optimal network conditions.
When uploading logs, you have the option to select a specific time frame, allowing you to reduce the volume of logs transmitted and shorten the upload duration.
To upload files, **go to Me → Support Tickets → Choose the ticket for log upload and proceed with the operation.**

<img width="858" height="1248" alt="Image" src="https://github.com/user-attachments/assets/2d2273e3-ea8c-445b-abde-d2979814763c" />

**Comment by aschubert-mathema** [comment]
Still an issue with newest version 2.2.0.85 on A1 Mini with 0.4mm nozzle on mac os. Reverting back again.

**Comment by fahaaaxiki** [comment]
> Still an issue with newest version 2.2.0.85 on A1 Mini with 0.4mm nozzle on mac os. Reverting back again.

May this problem be solved after returning to the previous Studio version?

**Comment by fahaaaxiki** [comment]
> Still an issue with newest version 2.2.0.85 on A1 Mini with 0.4mm nozzle on mac os. Reverting back again.

May this problem be solved after returning to the previous Studio version?

**Comment by aschubert-mathema** [comment]
Yes, as stated above: https://github.com/bambulab/BambuStudio/issues/7495#issuecomment-3048883062, last Version with flow calibration is V2.0.3.54. All versions thereafter are missing the calibration option as shown in the picture of threat opener @Stagecoachsi.

**Comment by fahaaaxiki** [comment]
> Yes, as stated above: [#7495 (comment)](https://github.com/bambulab/BambuStudio/issues/7495#issuecomment-3048883062), last Version with flow calibration is V2.0.3.54. All versions thereafter are missing the calibration option as shown in the picture of threat opener [@Stagecoachsi](https://github.com/Stagecoachsi).

Thank you for your feedback and we're very sorry for the inconvenience. We are making efforts to investigate and fix this issue. Once there is any progress, we will update it in this ticket later.

**Comment by Stagecoachsi** [comment]
Still experiencing this issue.

**Comment by Darius-bd** [comment]
I'm having the issue as well, there's no option, but the printer does a Dynamic Flow Calibration before every print and I have no way to stop that from happening. Printer firmware 01.03.01.02

**Comment by Darius-bd** [comment]
I've tested it with Bambu Studio 2.1.1 and there was the same issue. Then I installed 2.0.3 and in this version I have the option to turn on/off Flow Dynamic Calibration. 

In this version I can also see that is a dropdown option while in newer versions is a toggle. Perhaps just an UI problem? 

OS: Win 11 24H2

**Comment by JohnSmithCYM** [comment]
We have fixed the similar problem of H2S in V2.2.2.56，please try again.

**Comment by aschubert** [comment]
> We have fixed the similar problem of H2S in V2.2.2.56，please try again.

Seems also to have fixed it for me. A1 Mini latest firmware and V2.2.2.56 on Mac OS show Flow Calibration again. Thx!

**Comment by Darius-bd** [comment]
> We have fixed the similar problem of H2S in V2.2.2.56，please try again.

Alas, I've downloaded the latest version (v2.2.2.56) and I still don't have the option. Using in A1 Mini (not latest firmware tho). 

<img width="698" height="274" alt="Image" src="https://github.com/user-attachments/assets/d9573ace-36be-4d27-a3a9-c5f3aa07dea2" />

**Comment by XinZhangBambu** [comment]
@Darius-bd  Could you please give it a try to upgrade the firmware.

<img width="916" height="202" alt="Image" src="https://github.com/user-attachments/assets/02fe39af-43be-47b0-ae3f-a6d8f6d2bcbe" />

**Comment by Raekon** [comment]
I'm on version 2.4.0.70 and this is has become an issue for me too (though on A1 not mini). I don't know for how long. 
Is this a general fault?

-Morten

**Comment by nadnerb33** [comment]
@Raekon I just had the same issue and updating the printer firmware solved it for me.

**Comment by Raekon** [comment]
@nadnerb33 Hmm... As I feared... I would rather not update the firmware, unless absolutely necessary... You know... If it ain't broke, don't fix it-kinda thing... But thanks for the tip. Might be the leaser of two evils. 🙂
