### ISSUE TITLE
Clear seam is created when using spiral vase mode

### ISSUE THREAD

**Issue by ppamment** [bambulab/BambuStudio#753]
**Describe the bug**

When using spiral vase mode, I am often ending up with clear seams on the resulting print, and when I looked closely at the toolpath, they are also visible there. When observing the printer during printing, you can clearly also see the printer dwell for a moment at that spot, as though it is waiting there and moving z axis. This results in excess filament being deposited along that line and shows a very obvious seam. 

**3mf File for This Bug**
[vase_seam.zip](https://github.com/bambulab/BambuStudio/files/10141930/vase_seam.zip)

**To Reproduce**

I am using a solid model (a popular one from printables: https://www.printables.com/model/290951-a-slightly-overengineered-olpe-vase

Turned on spiral vase mode. 1 wall, 0 infill, no top layer.

I wondered if the seam was caused by retraction between layers, so tried disabling retraction in the filament overrides, but it gives the same result.

**Expected behavior**
I expect when printing in spiral vase mode for the printer to run in a continuous loop and not leave a seam.

**Screenshots**
Here you can see it in the generated gcode:
![image](https://user-images.githubusercontent.com/2122919/205315095-e4ff3fa3-8710-4192-93fd-30ec22da6eb2.png)

Here you can see it on the actual print:
![image](https://user-images.githubusercontent.com/2122919/205315690-81267b27-ffaf-42b3-a570-a4c5f2f208a3.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 1.03.01.01

**Comment by QingZhangBambu** [comment]
i use your 3mf and print it in BambuStudio X1C, the seam is Invisible.
there is the print result
![github](https://user-images.githubusercontent.com/112676417/207014194-3c1ad972-f7f7-4e89-bd70-2a9faf07c8f2.jpg)

**Comment by ppamment** [comment]
@QingZhangBambu Thanks. Not sure why we are seeing different results but it would be good to figure it out as I'm seeing it on multiple prints.

Please let me know if there is anything else you would like me to provide to help you debug.

For now here is another print where this happened: a purge bin for the printer:
![image](https://user-images.githubusercontent.com/2122919/207450507-17e0ec90-ca84-4da2-96e8-10394c451599.png)

3mf, step, and a video showing where this artifact is clearly present in the slicer as well as on the model:

[purge_bucket.zip](https://github.com/bambulab/BambuStudio/files/10222372/purge_bucket.zip)

Thanks

**Comment by QingZhangBambu** [comment]
@ppamment what filament you used? maybe it matters

**Comment by SaltWei** [comment]
For the video you shared, because this model has big shape change and some overhang at the first several layers, we do recommand that don't use too high layer height while using 0.42 line width. If you want to use 0.3 layer height, please incerase the line width as well, to avoid gaps in the first several layers.

For seams issue, we can't reproduce this issue in our printing. But we disable the timelapse when printing.
![image](https://user-images.githubusercontent.com/110660407/208059261-a21b9b89-1833-46a3-8507-c974d6227199.png)
Did you enable or disable the timelapse?

**Comment by SaltWei** [comment]
Has started one printing again with timelapse enabled. Will update one hour later when it finished

**Comment by SaltWei** [comment]
Still can't reproduce this issue. The 3MF I used and video are included in zip. Ignore the first layer which is not very well attached.

[3MF.zip](https://github.com/bambulab/BambuStudio/files/10245120/3MF.zip)
[video.zip](https://github.com/bambulab/BambuStudio/files/10245130/video.zip)
[timelapse.zip](https://github.com/bambulab/BambuStudio/files/10245132/timelapse.zip)


Pay attention that don't use smooth type timelapse in spiral vase mode. This will create seam. We will disable smooth type timelapse in spiral vase mode in next version.

**Comment by SaltWei** [comment]
Please see the latest message at https://github.com/bambulab/BambuStudio/issues/846, and update your printer firmware to be latest. This should solve the problem. So this issue is not caused by slicer but old printer firmware. Close

**Comment by gmoissey** [comment]
I can confirm **that this is not a printer issue but a problem with the slicer**. I'm trying to print with vase mode and a sliced preview has some artifacts on every layer. From what it looks like it is happening because of some tasks that a printer has to do between switching to the next layer. I attache
<img width="1727" alt="Screenshot 2023-05-15 at 11 53 14 AM" src="https://github.com/bambulab/BambuStudio/assets/69596008/899f1b0f-93e1-4590-97da-fd6cbbf659fd">
<img width="1307" alt="Screenshot 2023-05-15 at 11 54 49 AM" src="https://github.com/bambulab/BambuStudio/assets/69596008/7774c862-cfe3-4099-8ab3-24039922aa86">
d two screenshots

**Comment by QuiNz0r** [comment]
This issue still persists, any ideas? 
![problem](https://github.com/bambulab/BambuStudio/assets/16562386/7bf99798-522b-4c75-84e0-fd0fc8061c93)

**Comment by bzwart77** [comment]
Hello, this problem is real and impacting all vase mode models many are printing on x1 and a P1P.  This issue is becoming more known as seen in these [posts1 ](https://www.reddit.com/r/BambuLab/comments/17qqmr8/vase_mode_vertical_line_appearing_when_using/)and [posts2](https://www.reddit.com/r/BambuLab/comments/11cn3ir/how_do_i_get_rid_of_or_at_least_move_this/)

**Comment by Xarbenence** [comment]
I am still getting this issue. I am using Bambu Slicer 1.8.4.51, and a Bambu P1S.

**Comment by QingZhangBambu** [comment]
@Xarbenence please update the latest version

**Comment by QingZhangBambu** [comment]
![image](https://github.com/bambulab/BambuStudio/assets/112676417/80bdc377-ce1f-42c2-a753-c13872b1f58b)
![image](https://github.com/bambulab/BambuStudio/assets/112676417/ad3a3cf6-cb9c-4286-a701-e49f86344d3f)
@Xarbenence this function may help

**Comment by Xarbenence** [comment]
Thank you, @QingZhangBambu!
