### ISSUE TITLE
Crash on Slice - Very Repeatable

### ISSUE THREAD

**Issue by leoalexanderLINKAM** [bambulab/BambuStudio#7633]
### Bambu Studio Version

v02.1.1.52

### Where is the application from?

Bambu Lab Official website

### OS version

OS: Windows 11

### Additional system information

Processor	                                  Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz, 3000 Mhz, 8 Core(s), 8 Logical Processor(s)
Installed Physical Memory (RAM)	  32.0 GB
System Type	                                  x64-based PC
Graphics                                           NVIDIA Quadro P2000

### Printer

Bambu Lab X1C

### How to reproduce

Open any model and attempt to slice. 9/10 times it will crash in the last steps. If it does manage to slice, it will likely crash sending to printer.
When software was initially updated there was no issue. This has occurred after several days on the latest version.

### Actual results

Program crashes. No error message shown.

### Expected results

No crash.

### Project file & Debug log uploads

[Rugged_Organizer_XXXL_4x6_1C.zip](https://github.com/user-attachments/files/21346651/Rugged_Organizer_XXXL_4x6_1C.zip)

[log.zip](https://github.com/user-attachments/files/21346714/log.zip)

### Checklist of files to include

- [x] Log file
- [x] Project file

**Comment by JiaYun-Bambu** [comment]
Hello, thank you for your feedback. We have released a new version that addresses some crash-related issues. Please try downloading and using the updated software to see if it resolves your problem. Thank you for your support!
https://github.com/bambulab/BambuStudio/releases/tag/v02.02.00.60

**Comment by leoalexanderLINKAM** [comment]
> Hello, thank you for your feedback. We have released a new version that addresses some crash-related issues. Please try downloading and using the updated software to see if it resolves your problem. Thank you for your support! https://github.com/bambulab/BambuStudio/releases/tag/v02.02.00.60

Hi JiaYun,
Thank you for your response. Sadly this did not fix the issue. I repeated my steps from before and immediately saw the crash.

**Comment by JiaYun-Bambu** [comment]
Thank you for sharing the detailed information.
We see that you’re experiencing frequent crashes during slicing and sending tasks. This may be related to your NVIDIA Quadro GPU setup.
Please refer to this community thread where other users have discussed and resolved similar issues:
https://forum.bambulab.com/t/bambu-studio-crashes-after-slicing-solved-nvidia-problem/162392
If the issue still persists after trying the suggestions in that post, please let us know — we’ll arrange for the development team to check further if needed.
Thank you for your patience and support!

**Comment by leoalexanderLINKAM** [comment]
This worked! Thanks very much 🙂


Kind Regards,

Leo Alexander





Linkam Scientific Instruments Ltd.

Mechanical Development Engineer



Phone:  +44 (0) 1737 363 476 EXT 236



­[cid:bb5f283f-2080-4cdc-bbda-3d418aee433f]<http://www.linkam.co.uk/>   [cid:21b3f783-5157-4960-98e1-a42be288da12] <https://www.linkedin.com/company/8288338/>    [cid:fe76de37-dac9-4137-a7ea-daad41ed68af] <https://www.instagram.com/linkamscientific/>    [cid:c6f90f83-a18d-4919-8650-72c977f41117] <https://twitter.com/linkamstages>

[cid:45559923-e6a4-412c-ac79-f27580721f79]

Registered Office: Unit 9, Perrywood Business Park, Honeycrock Lane,

Salfords, Redhill, Surrey RH1 5DZ, UK



VAT No. GB 220 0780 15     Company No. 1671841    D-U-N-S Number: 291368496



This e-mail may contain confidential and/or privileged information.

If you are not the intended recipient or have received this e-mail
in error, please notify the sender immediately and destroy this e-mail.
Any unauthorised copying, disclosure or distribution of the material
in this e-mail is strictly forbidden.



________________________________
