### ISSUE TITLE
Bambu Studio crashes when loading .gcode file

### ISSUE THREAD

**Issue by rookuu** [bambulab/BambuStudio#7706]
### Bambu Studio Version

2.1.1.52

### Where is the application from?

Bambu Lab Official website

### OS version

macOS 26

### Additional system information

Apple M3 Pro
36GB RAM

### Printer

P1S

### How to reproduce

1. Load external gcode file by opening it in Bambu Studio
2. Bambu Studio hangs on `loading Gcode`

### Actual results

<img width="1624" height="1060" alt="Image" src="https://github.com/user-attachments/assets/0aac21fc-9fe6-439f-ab52-865349410199" />

### Expected results

It loads the file

### Project file & Debug log uploads

[DishwasherStatus_PLA_18m30s.gcode.zip](https://github.com/user-attachments/files/21514745/DishwasherStatus_PLA_18m30s.gcode.zip)

[debug_Wed_Jul_30_18_08_06_73652.log.0.zip](https://github.com/user-attachments/files/21514828/debug_Wed_Jul_30_18_08_06_73652.log.0.zip)

### Checklist of files to include

- [x] Log file
- [x] Project file

**Comment by JinGangBambu** [comment]
Hello, thank you for your report!
This issue has been identified and will be fixed in an upcoming version in the near future.
We appreciate your patience and understanding — sorry for the inconvenience!

**Comment by will-reynolds** [comment]
Thanks for your help. Is there an ETA for this fix? Is it also possible to share which historic version I should roll back to?

**Comment by xxrxndxvxs** [comment]
I have a similar issue when loading larger gcode files. Smaller files seem fine. I am also using an Apple M3 (Max) w/ 36 GB Ram. Where it hangs varies slightly each time I try, but ends up looking like this image, before BambuStudio becomes unresponsive.![image](https://github.com/user-attachments/assets/04dcd575-3abe-4534-936f-b3f263f409d2)

**Comment by JinGangBambu** [comment]
@will-reynolds Hello, this issue has been resolved. Please try using the latest version V2.2.1.60. If you have any problems, please feel free to let us know. Download link:https://github.com/bambulab/BambuStudio/releases

**Comment by ShanCang-BamBu** [comment]
@xxrxndxvxs 
Hello, thank you for your feedback!
We recommend using the latest version of Studio, which you can download here:
https://github.com/bambulab/BambuStudio/releases
If the issue still occurs, please provide the corresponding 3MF file so we can reproduce it right away and work on fixing the bug.
Thank you for your support and understanding!

**Comment by will-reynolds** [comment]
I'm afraid that this latest version of Bambu Studio doesn't solve the issue for me on my Mac:
<img width="825" height="530" alt="Image" src="https://github.com/user-attachments/assets/9a1ccec8-026d-4ebd-a380-546752eaea21" />
<img width="308" height="512" alt="Image" src="https://github.com/user-attachments/assets/de4652c6-87bf-4252-a662-25ad9cb2d437" />

When I drag and drop the following file (please change the suffix to `.gcode` after downloading) into the `Preview` window in Bambu Studio, it freezes during the import, as shown above:

**Comment by will-reynolds** [comment]
For some reason, github isn't accepting the file, even if I upload it as a .txt file, simply saying 'Failed to upload'.

**Comment by will-reynolds** [comment]
[troublesome_geometry.gcode.zip](https://github.com/user-attachments/files/22090135/troublesome_geometry.gcode.zip)

**Comment by BoBoYu-BamBu** [comment]
Thank you for your feedback. This issue has been fixed. Please update to the latest version of Studio for verification. Download link: https://bambulab.cn/zh-cn/download/studio
