### ISSUE TITLE
Support wrong when adaptive layer height is enabled

### ISSUE THREAD

**Issue by hutje** [bambulab/BambuStudio#826]
**Describe the bug**
Support doesn't work correctly when adaptive layer height is enabled.

**3mf File for This Bug**
[Bad day test.zip](https://github.com/bambulab/BambuStudio/files/10231204/Bad.day.test.zip)

**To Reproduce**
1. Import 3mf
2. Slice with adaptive layer height enabled

**Expected behavior**
Same as it would produce support when adaptive layer height is turned off

**Screenshots**
![image](https://user-images.githubusercontent.com/15308350/207701647-ce215ed0-e29a-46f3-9c7d-edc6e9567844.png)
![image](https://user-images.githubusercontent.com/15308350/207701828-90fffd7d-9c58-433d-b455-b5d07b39d801.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version BambuStudio V01.03.01.01

**Comment by hutje** [comment]
Also this model gives the same problems. 
[Hips HQ Mesh Bambulab.zip](https://github.com/bambulab/BambuStudio/files/10239586/Hips.HQ.Mesh.Bambulab.zip)

Desktop (please complete the following information):

OS: Windows 10
Version BambuStudio V1.4.0.17

**Comment by hutje** [comment]
Close was a mistake...

**Comment by tangketan** [comment]
The issue is fixed in the latest version: https://github.com/bambulab/BambuStudio/releases/tag/v01.04.01.52

**Comment by hutje** [comment]
Not fixed entirely. I seem to have the same issues, but now with other models. Will upload 3mf file tomorrow.

**Comment by tangketan** [comment]
@hutje Hi~ any change to get the 3mf?
