### ISSUE TITLE
"Add Part" not properly aligned to parent object

### ISSUE THREAD

**Issue by toddanglin** [bambulab/BambuStudio#980]
There appears to be a regression bug in the latest Bambu Studio (v 1.4.0.18, macOS 12.6) that causes parts added to an object to be improperly positioned. (I have also validated that this behavior/bug still exists in v 1.4.1.52 beta build.)

**Expected Behavior (and Bambu Studio behavior pre-v1.4.x)**
1. Import a 3MF object in Bambu Studio
2. Right-click object, choose "Add part..."
3. Choose a different 3MF object file that represents a different part of the design
4. New part object is added in correct relative position to the parent object

**Actual behavior (in v 1.4.0.18)**
1. Import 3MF object in Bambu Studio
2. Right-click object, "Add part..."
3. Choose a part object
4. New part pbject is positioned directly on the print plate surface, not in the correct relative position to the base object

It seems the local/relative coordinate system of the objects is being ignored. This works properly, as expected in Bambu Studio v 1.03.01.01 (last stable release before 1.4.x).

**Comment by toddanglin** [comment]
**Extra context:**
- I'm working with multi-part objects exported from Fusion 360 as multiple, separate 3MF files
- I load the "base" 3MF file, and then attempt to add the "children" parts from separate 3MF files
- In the past, this would correctly position the parts relative to the "base"

**Work around:**
- If you export all parts from Fusion360 as a single, multi-part 3MF file and load that in Bambu Studio, the parts will be correctly positioned

**Comment by SaltWei** [comment]
@zhimin-zeng-bambulab Please help to comfirm whether the behaviour is as expect

**Comment by MadMax389** [comment]
Not working for me as well in v1.4 in a complex project with a lot of parts. It was working in v1.3.

**Comment by zhimin-zeng-bambulab** [comment]
I try to reproduce this problem, but it doesn't seem to work. The picture below is what I did.
I found that the newly added object is always in the lower right corner of the original object.

![image](https://user-images.githubusercontent.com/120697589/211530939-38e590c2-cfae-4521-9bf4-f2fd67b5e9aa.png)

**Comment by zhimin-zeng-bambulab** [comment]
Could you provide your 3mf file, and the sub-part obejct file?  It will help us to solve the problem, thanks!

**Comment by zhimin-zeng-bambulab** [comment]
Thanks a lot，we will fix it in future version.

**Comment by SaltWei** [comment]
FIx is available in v1.5.0 Public Beta

**Comment by SaltWei** [comment]
FIx is available in v1.5.0 Public Beta

**Comment by Bathsheba** [comment]
This is not fixed. Added parts, and parts imported at the same time all drop to the build bed. They are not correctly positioned relative to each other.

**Comment by SaltWei** [comment]
> This is not fixed. Added parts, and parts imported at the same time, all drop to the build bed. They are not correctly positioned relative to each other.

@zhimin-zeng-bambulab Please check and respond

**Comment by zhimin-zeng-bambulab** [comment]
@Bathsheba  Could you share your 3mf file?  And could you use a picture to show your problem？

**Comment by MadMax389** [comment]
I can confirm this behavior (v1.8.4.51). Image on the right, both stls loaded on the plate at the same time and assembled as one object. Image on the left, loaded car body first, then loaded window as a part...
![image](https://github.com/bambulab/BambuStudio/assets/96731892/d8b75f09-9e85-424a-b11c-c5d2c53e0ef0)

**Comment by Bathsheba** [comment]
> @Bathsheba Could you share your 3mf file? And could you use a picture to show your problem？

Sorry I didn't keep the file, it occurred in the context of trying to print a part in one filament completely enclosed by another part in another (translucent) filament. 
I was trying to create a part with a negative area floating inside it, and a second part occupying that area. I was not able to do this. Thanks for your consideration.

**Comment by zhimin-zeng-bambulab** [comment]
@MadMax389 Could you share your stl files to help us solve this problem?

**Comment by MadMax389** [comment]
I created a new example. 
This is a Fusion 360 drawing of two stacked cubes. Each body was exported separately. Cube stls are attached in zip file.
![image](https://github.com/bambulab/BambuStudio/assets/96731892/28a5f556-5b98-48fc-a19c-4c758b05ca24)

In this image on the left plate, both cube stls were added to the plate together and assembled as one object. On the right plate, the lower cube was added first and the upper cube was added as a part.
![image](https://github.com/bambulab/BambuStudio/assets/96731892/9a2114fc-7818-4a5b-88c1-3a95f0e2ef41)

Prusa Slicer handles this operation properly,
![image](https://github.com/bambulab/BambuStudio/assets/96731892/1aad249d-3334-44ec-85a5-e05ba8bdb9bc)

[Cubes.zip](https://github.com/bambulab/BambuStudio/files/14017840/Cubes.zip)

**Comment by zhimin-zeng-bambulab** [comment]
it has been fixed in v01.09.00.06
